[package]
name = "nuklear-sample-extended"
version = "0.2.0"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "~0.3", features = ["rust_allocator"], path = "../nuklear-rust"}
nuklear-backend-gfx = {version = "~0.4", path = "../nuklear-backend-gfx"}
gfx_device_gl = "~0.14"
gfx_window_glutin = "~0.15"
gfx = "~0.15"
glutin = "~0.7"
image = "~0.12"

[[bin]]
name = "t"
path = "src/main.rs"