[package]
name = "nuklear-sample-extended"
version = "0.1.3"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "*"}
nuklear-backend-gfx = { version = "*", path = "../nuklear-backend-gfx" }
gfx_device_dx11 = "*"
gfx_window_dxgi = "*"
winit = "*"
gfx = "*"
image = "*"

[[bin]]
name = "t"
path = "src/main.rs"