[package]
name = "nuklear-sample-extended"
version = "0.1.0"
authors = ["snuk182 <snuk188@gmail.com>"]
edition = "2018"

[dependencies]
nuklear-rust = {version = "~0.6", features = ["rust_allocator"]}
nuklear-backend-wgpurs = {version = "~0.1", features = ["vulkan"]}
wgpu = "~0.2"
image = "~0.21"

[[bin]]
name = "t"
path = "src/main.rs"
