[package]
name = "nuklear-sample-extended"
version = "0.1.3"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "*", features = ["rust_allocator"]}
nuklear-backend-gfx = { version = "*" }
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx = "*"
glutin = "~0.6"
image = "*"

[[bin]]
name = "t"
path = "src/main.rs"