[package]
name = "nr-test"
version = "0.1.0"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "*", features = ["rust_allocator"]}
nuklear-backend-glium = { version = "*", path = "../nuklear-backend-glium"}
glium = "*"
glutin = "*"
image = "*"

[[bin]]
name = "t"
path = "src/main.rs"