[package]
name = "nuklear-sample-extended"
version = "0.1.3"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "*", features = ["rust_allocator"]}
nuklear-backend-gfx = { version = "*", path = "../nuklear-backend-gfx" }
gfx_device_gl = { version = "*", path = "../gfx/src/backend/gl" }
gfx_window_glutin = { version = "*", path = "../gfx/src/window/glutin" }
gfx = { version = "*", path = "../gfx/src/render" }
glutin = "*"
image = "*"

[[bin]]
name = "t"
path = "src/main.rs"