[package]
name = "nuklear-sample-extended"
version = "0.1.0"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "~0.4", features = ["rust_allocator"]}
nuklear-backend-gdi = {version = "~0.2", features = ["piston_image"]}
winapi = {version = "~0.3", features = ["windef", "minwindef", "winuser", "winbase", "wingdi"]}
image = "*"

[[bin]]
name = "t"
path = "src/main.rs"