[package]
name = "nuklear-sample-extended"
version = "0.2.0"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "~0.3", features = ["rust_allocator"]}
nuklear-backend-gfx = "~0.5"
gfx_device_dx11 = "~0.6"
gfx_window_dxgi = "~0.7"
winit = "~0.5"
gfx = "~0.16"
image = "~0.12"

[[bin]]
name = "t"
path = "src/main.rs"