[package]
name = "nuklear-sample-extended"
version = "0.2.1"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "~0.3", features = ["rust_allocator"]}
nuklear-backend-gfx = "~0.5"
gfx_device_gl = "~0.14"
gfx_window_glutin = "~0.16"
gfx = "~0.16"
glutin = "~0.8"
image = "~0.12"

[[bin]]
name = "t"
path = "src/main.rs"