[package]
name = "nuklear-sample-extended"
version = "0.3.0"
authors = ["snuk182 <snuk188@gmail.com>"]
edition = "2018"

[dependencies]
nuklear-rust = {version = "~0.6", features = ["rust_allocator"]}
nuklear-backend-gfx = "~0.8"
gfx_device_dx11 = "~0.7"
gfx_window_dxgi = "~0.11"
winit = "~0.10"
gfx = "~0.17"
image = "~0.12"

[[bin]]
name = "t"
path = "src/main.rs"