[package]
name = "nuklear-sample-extended"
version = "0.1.3"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "*", features = ["rust_allocator"]}
nuklear-backend-gfx = "~0.2"
gfx_device_dx11 = "~0.5"
gfx_window_dxgi = "~0.6"
winit = "~0.5"
gfx = "~0.14"
image = "~0.12"

[[bin]]
name = "t"
path = "src/main.rs"