[package]
name = "nuklear-sample-extended"
version = "0.1.3"
authors = ["snuk182 <snuk188@gmail.com>"]

[dependencies]
nuklear-rust = {version = "~0.2", features = ["rust_allocator"]}
nuklear-backend-gfx = {version = "~0.3", path="../nuklear-backend-gfx" }
gfx_device_dx11 = "~0.6"
gfx_window_dxgi = "~0.7"
winit = "~0.5"
gfx = "~0.15"
image = "~0.12"

[[bin]]
name = "t"
path = "src/main.rs"